on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "pypy-3.10"
          - "graalpy-24"
        arch:
          - x86_64
          - aarch64
        platform:
          - linux
          - musllinux
          - windows
          - macos

        exclude:
          - platform: windows
            python-version: graalpy-24
          - platform: windows
            arch: aarch64

        include:
          - wheel: "3.x"
          - python-version: "pypy-3.10"
            wheel: "pypy-3.10"
          - python-version: "graalpy-24"
            wheel: "graalpy-24"

          - runs: ubuntu-latest
          - platform: windows
            runs: windows-latest
          - platform: macos
            runs: macos-latest
            
    steps:
      - name: thing
        run: |
          echo runs ${{ matrix.runs }}
          echo python ${{ matrix.python-version }}
          echo wheels-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.wheel }}
          test "${{ matrix.runs }}"
